language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_script:
  - pip install -r requirements.txt
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# command to run tests
script:
  - python -m pytest --cov=./ --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT